name: NPM Package Release

on:
  push:
    branches:
      - production
jobs:
  create-package:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@dijkstra-solution"

      - name: Install dependencies
        run: npm ci

      - name: Configure npmrc for GitHub Packages
        run: |
          echo "@dijkstra-solution:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Setup github actor
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Build the app
        run: npm run build

      - name: Publish package
        run: npm run release
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

